import { createContext, useContext, useState } from 'react';

// ── Translations ──────────────────────────────────────────────────────────────
const T = {
  en: {
    nav: {
      navigation:   'Navigation',
      dashboard:    'Dashboard',
      allListings:  'All Listings',
      addListing:   'Add Listing',
      flatMate:     'Flat Mate',
      installApp:   'Install App',
      installSub:   'Open without a browser',
    },
    dashboard: {
      morning:      'Good morning',
      afternoon:    'Good afternoon',
      evening:      'Good evening',
      subtitle:     "Here's your accommodation overview for today.",
      addListing:   'Add Listing',
      totalListings:'Total Listings',
      available:    'Available',
      unavailable:  'Unavailable',
      avgPrice:     'Avg. Monthly Price',
      allProperties:'All properties',
      ofTotal:      '% of total',
      acrossAll:    'Across all listings',
      recentListings:'Recent Listings',
      viewAll:      'View all',
      noListings:   'No listings yet',
      addedBy:      'Added by',
      byType:       'Listings by Property Type',
      byBedrooms:   'Listings by Bedrooms',
      byAvailability:'Availability Status',
      byAudience:   'Target Audience',
    },
    listings: {
      title:        'Listings',
      loading:      'Loading…',
      found1:       'property found',
      foundMany:    'properties found',
      exportPdf:    'Export PDF',
      exportExcel:  'Export Excel',
      email:        'Email',
      addListing:   'Add Listing',
      noMatch:      'No listings match your filters',
      clearFilters: 'Clear filters',
      view:         'View',
      edit:         'Edit',
      noImage:      'No image',
      tableType:    'Type',
      tablePrice:   'Price',
      tableAddress: 'Address',
      tableStatus:  'Status',
      tableLandlord:'Landlord',
    },
    filters: {
      title:        'Filters',
      reset:        'Reset',
      search:       'Search',
      searchPlaceholder: 'Address, landlord…',
      phone:        'Phone Number',
      phonePlaceholder: '+357 99…',
      availability: 'Availability',
      all:          'All',
      available:    'Available',
      unavailable:  'Unavailable',
      propertyType: 'Property Type',
      allTypes:     'All Types',
      bedrooms:     'Bedrooms',
      any:          'Any',
      priceRange:   'Price Range',
      min:          'Min',
      max:          'Max',
      audience:     'Target Audience',
      fullTime:     'Full-time',
      erasmus:      'Erasmus',
      walkingOnly:  'Walking distance only',
      availDates:   'Available From / To',
    },
    property: {
      apartment:    'Apartment',
      studio:       'Studio',
      house:        'House',
      room:         'Room',
      bed:          'bed',
      beds:         'beds',
      fullyFurnished:'Fully Furnished',
      semiFurnished: 'Semi-Furnished',
      walkingDist:  'Walking distance',
      allStudents:  'All Students',
      erasmus:      'Erasmus',
      fullTime:     'Full-time Students',
      perMonth:     '/mo',
      perMonthLong: '/month',
      addedBy:      'Added by',
      availFrom:    'From',
      immediately:  'Immediately',
    },
    flatmates: {
      title:        'Flatmate Finder',
      subtitle:     'Students looking for flatmates or flats to share',
      addStudent:   'Add Student',
      allStudents:  'All Students',
      hasFlat:      'Has a Flat',
      lookingForFlat:'Looking for a Flat',
      noStudents:   'No students found',
      addFirst:     'Add First Student',
      addTitle:     'Add Student to Flatmate List',
      firstName:    'First Name',
      lastName:     'Last Name',
      phone:        'Phone Number',
      email:        'Email Address',
      year:         'Year of Study',
      gender:       'Gender',
      status:       'Flatmate Status',
      notes:        'Notes',
      hasAFlat:     'Has a Flat',
      hasAFlatSub:  'Looking for a flatmate',
      lookingFlat:  'Looking for a Flat',
      lookingFlatSub:'Wants to share with someone',
      addedBy:      'Added by',
      allGenders:   'All Genders',
      allYears:     'All Years',
      male:         'Male',
      female:       'Female',
      preferNot:    'Prefer not to say',
      cancel:       'Cancel',
      saving:       'Saving…',
      save:         'Add Student',
      remove:       'Remove',
      notesPlaceholder: 'Any additional details…',
      searchPlaceholder:'Search by name, phone, email…',
      selectYear:   'Select year…',
    },
    common: {
      loading:      'Loading…',
      save:         'Save',
      cancel:       'Cancel',
      delete:       'Delete',
      edit:         'Edit',
      view:         'View',
      back:         'Back',
      backToListings:'Back to Listings',
      backToListing: 'Back to Listing',
      proceedAnyway:'Proceed Anyway',
      goBack:       'Go Back',
      required:     'Required',
      optional:     '(optional)',
      sending:      'Sending…',
      send:         'Send Email',
      retry:        'Retry',
      signOut:      'Sign Out',
      signedInAs:   'Signed in as',
      settings:     'Account Settings',
      duplicateTitle:'Possible Duplicate Detected',
      duplicateSub: 'A landlord with matching details already exists in the system.',
      duplicateQ:   'Do you still want to add this as a new listing?',
      noData:       'No data yet',
    },
  },

  // ── Greek ───────────────────────────────────────────────────────────────────
  el: {
    nav: {
      navigation:   'Πλοήγηση',
      dashboard:    'Πίνακας Ελέγχου',
      allListings:  'Όλες οι Αγγελίες',
      addListing:   'Νέα Αγγελία',
      flatMate:     'Συγκάτοικος',
      installApp:   'Εγκατάσταση',
      installSub:   'Άνοιγμα χωρίς περιηγητή',
    },
    dashboard: {
      morning:      'Καλημέρα',
      afternoon:    'Καλό απόγευμα',
      evening:      'Καλησπέρα',
      subtitle:     'Επισκόπηση στεγαστικών επιλογών για σήμερα.',
      addListing:   'Νέα Αγγελία',
      totalListings:'Σύνολο Αγγελιών',
      available:    'Διαθέσιμα',
      unavailable:  'Μη Διαθέσιμα',
      avgPrice:     'Μέση Μηνιαία Τιμή',
      allProperties:'Όλα τα ακίνητα',
      ofTotal:      '% επί του συνόλου',
      acrossAll:    'Σε όλες τις αγγελίες',
      recentListings:'Πρόσφατες Αγγελίες',
      viewAll:      'Εμφάνιση όλων',
      noListings:   'Δεν υπάρχουν αγγελίες',
      addedBy:      'Προστέθηκε από',
      byType:       'Αγγελίες ανά Τύπο Ακινήτου',
      byBedrooms:   'Αγγελίες ανά Υπνοδωμάτια',
      byAvailability:'Κατάσταση Διαθεσιμότητας',
      byAudience:   'Κοινό-Στόχος',
    },
    listings: {
      title:        'Αγγελίες',
      loading:      'Φόρτωση…',
      found1:       'ακίνητο βρέθηκε',
      foundMany:    'ακίνητα βρέθηκαν',
      exportPdf:    'Εξαγωγή PDF',
      exportExcel:  'Εξαγωγή Excel',
      email:        'Email',
      addListing:   'Νέα Αγγελία',
      noMatch:      'Δεν βρέθηκαν αγγελίες με αυτά τα φίλτρα',
      clearFilters: 'Καθαρισμός φίλτρων',
      view:         'Προβολή',
      edit:         'Επεξεργασία',
      noImage:      'Χωρίς εικόνα',
      tableType:    'Τύπος',
      tablePrice:   'Τιμή',
      tableAddress: 'Διεύθυνση',
      tableStatus:  'Κατάσταση',
      tableLandlord:'Ιδιοκτήτης',
    },
    filters: {
      title:        'Φίλτρα',
      reset:        'Επαναφορά',
      search:       'Αναζήτηση',
      searchPlaceholder: 'Διεύθυνση, ιδιοκτήτης…',
      phone:        'Αριθμός Τηλεφώνου',
      phonePlaceholder: '+357 99…',
      availability: 'Διαθεσιμότητα',
      all:          'Όλα',
      available:    'Διαθέσιμο',
      unavailable:  'Μη Διαθέσιμο',
      propertyType: 'Τύπος Ακινήτου',
      allTypes:     'Όλοι οι Τύποι',
      bedrooms:     'Υπνοδωμάτια',
      any:          'Οποιοδήποτε',
      priceRange:   'Εύρος Τιμής',
      min:          'Ελάχ.',
      max:          'Μέγ.',
      audience:     'Κοινό-Στόχος',
      fullTime:     'Κανονικοί',
      erasmus:      'Erasmus',
      walkingOnly:  'Μόνο κοντινή απόσταση',
      availDates:   'Διαθέσιμο Από / Έως',
    },
    property: {
      apartment:    'Διαμέρισμα',
      studio:       'Στούντιο',
      house:        'Σπίτι',
      room:         'Δωμάτιο',
      bed:          'υπνοδ.',
      beds:         'υπνοδ.',
      fullyFurnished:'Πλήρως Επιπλωμένο',
      semiFurnished: 'Μερικώς Επιπλωμένο',
      walkingDist:  'Κοντινή απόσταση',
      allStudents:  'Όλοι οι Φοιτητές',
      erasmus:      'Erasmus',
      fullTime:     'Κανονικοί Φοιτητές',
      perMonth:     '/μήνα',
      perMonthLong: '/μήνα',
      addedBy:      'Προστέθηκε από',
      availFrom:    'Από',
      immediately:  'Άμεσα',
    },
    flatmates: {
      title:        'Αναζήτηση Συγκατοίκου',
      subtitle:     'Φοιτητές που αναζητούν συγκατοίκους ή διαμερίσματα για κοινή διαμονή',
      addStudent:   'Προσθήκη Φοιτητή',
      allStudents:  'Όλοι οι Φοιτητές',
      hasFlat:      'Έχει Διαμέρισμα',
      lookingForFlat:'Ψάχνει Διαμέρισμα',
      noStudents:   'Δεν βρέθηκαν φοιτητές',
      addFirst:     'Προσθήκη Πρώτου Φοιτητή',
      addTitle:     'Προσθήκη Φοιτητή στη Λίστα',
      firstName:    'Όνομα',
      lastName:     'Επώνυμο',
      phone:        'Αριθμός Τηλεφώνου',
      email:        'Διεύθυνση Email',
      year:         'Έτος Σπουδών',
      gender:       'Φύλο',
      status:       'Κατάσταση',
      notes:        'Σημειώσεις',
      hasAFlat:     'Έχει Διαμέρισμα',
      hasAFlatSub:  'Ψάχνει συγκάτοικο',
      lookingFlat:  'Ψάχνει Διαμέρισμα',
      lookingFlatSub:'Θέλει να μοιραστεί διαμέρισμα',
      addedBy:      'Προστέθηκε από',
      allGenders:   'Όλα τα φύλα',
      allYears:     'Όλα τα έτη',
      male:         'Άνδρας',
      female:       'Γυναίκα',
      preferNot:    'Προτιμώ να μην αναφέρω',
      cancel:       'Ακύρωση',
      saving:       'Αποθήκευση…',
      save:         'Προσθήκη Φοιτητή',
      remove:       'Αφαίρεση',
      notesPlaceholder: 'Τυχόν επιπλέον πληροφορίες…',
      searchPlaceholder:'Αναζήτηση με όνομα, τηλέφωνο, email…',
      selectYear:   'Επιλέξτε έτος…',
    },
    common: {
      loading:      'Φόρτωση…',
      save:         'Αποθήκευση',
      cancel:       'Ακύρωση',
      delete:       'Διαγραφή',
      edit:         'Επεξεργασία',
      view:         'Προβολή',
      back:         'Πίσω',
      backToListings:'Πίσω στις Αγγελίες',
      backToListing: 'Πίσω στην Αγγελία',
      proceedAnyway:'Συνέχεια παρόλα αυτά',
      goBack:       'Πίσω',
      required:     'Υποχρεωτικό',
      optional:     '(προαιρετικό)',
      sending:      'Αποστολή…',
      send:         'Αποστολή Email',
      retry:        'Επανάληψη',
      signOut:      'Αποσύνδεση',
      signedInAs:   'Συνδεδεμένος ως',
      settings:     'Ρυθμίσεις Λογαριασμού',
      duplicateTitle:'Πιθανό Διπλότυπο',
      duplicateSub: 'Ένας ιδιοκτήτης με παρόμοια στοιχεία υπάρχει ήδη στο σύστημα.',
      duplicateQ:   'Θέλετε να προσθέσετε αυτή την αγγελία παρόλα αυτά;',
      noData:       'Δεν υπάρχουν δεδομένα',
    },
  },
};

// ── Context ───────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem('unic_lang') || 'en'
  );

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem('unic_lang', l);
  };

  // Dot-notation getter: t('dashboard.title')
  const t = (path) => {
    const keys = path.split('.');
    let node = T[lang];
    for (const k of keys) {
      node = node?.[k];
      if (node === undefined) return path;
    }
    return node ?? path;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
